package com.river.test;

import java.util.Date;

public class MessageRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.relation_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private String relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.message_type
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private Integer messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.message_status
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private Integer messageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.receiver_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private String receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.sender_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private String senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.executor_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private String executorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.version
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.is_delete
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.creator_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.create_date
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.modifier_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private String modifierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.modify_date
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.remark
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.message
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.id
     *
     * @return the value of message_record.id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.id
     *
     * @param id the value for message_record.id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.relation_id
     *
     * @return the value of message_record.relation_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public String getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.relation_id
     *
     * @param relationId the value for message_record.relation_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setRelationId(String relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.message_type
     *
     * @return the value of message_record.message_type
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.message_type
     *
     * @param messageType the value for message_record.message_type
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.message_status
     *
     * @return the value of message_record.message_status
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public Integer getMessageStatus() {
        return messageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.message_status
     *
     * @param messageStatus the value for message_record.message_status
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setMessageStatus(Integer messageStatus) {
        this.messageStatus = messageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.receiver_id
     *
     * @return the value of message_record.receiver_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.receiver_id
     *
     * @param receiverId the value for message_record.receiver_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.sender_id
     *
     * @return the value of message_record.sender_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.sender_id
     *
     * @param senderId the value for message_record.sender_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.executor_id
     *
     * @return the value of message_record.executor_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public String getExecutorId() {
        return executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.executor_id
     *
     * @param executorId the value for message_record.executor_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setExecutorId(String executorId) {
        this.executorId = executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.version
     *
     * @return the value of message_record.version
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.version
     *
     * @param version the value for message_record.version
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.is_delete
     *
     * @return the value of message_record.is_delete
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.is_delete
     *
     * @param isDelete the value for message_record.is_delete
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.creator_id
     *
     * @return the value of message_record.creator_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.creator_id
     *
     * @param creatorId the value for message_record.creator_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.create_date
     *
     * @return the value of message_record.create_date
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.create_date
     *
     * @param createDate the value for message_record.create_date
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.modifier_id
     *
     * @return the value of message_record.modifier_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.modifier_id
     *
     * @param modifierId the value for message_record.modifier_id
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.modify_date
     *
     * @return the value of message_record.modify_date
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.modify_date
     *
     * @param modifyDate the value for message_record.modify_date
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.remark
     *
     * @return the value of message_record.remark
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.remark
     *
     * @param remark the value for message_record.remark
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.message
     *
     * @return the value of message_record.message
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.message
     *
     * @param message the value for message_record.message
     *
     * @mbggenerated Mon Sep 03 15:55:08 CST 2018
     */
    public void setMessage(String message) {
        this.message = message;
    }
}